version: '3'

services:
  mymongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"

  web:
    build: .
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mymongo
    volumes:
      - ./app.py:/app/app.py